### ISSUE TITLE
Peer to peer code review to Maria's Contact form

### ISSUE THREAD

**Issue by rex-9** [Maria18000/Portfolio--setup-and-mobile-version-skeleton#5]
Contact form template 1

**Comment by rex-9** [comment]
It is a really great work! 
Need some padding.

**Comment by AsimKhan2019** [comment]
I think that the Line issue is being caused due to the flex display and the flex-direction. Maybe we can use the position relative or absolute to the HR tag

**Comment by AsimKhan2019** [comment]
I think the <hr > should have a closing tag as well. Like this <hr></hr> or <hr/>

**Comment by AsimKhan2019** [comment]
Try this 
<ul>
<li>
<hr />
</li>
</ul>

In the style.css use 
display:block;
list-style:none;

**Comment by Maria18000** [comment]
Only contact form was showed for review. The other changes were still in progress at that time and the project has been approved.
